config/routes.rb
Notebook::Application.routes.draw do

  resources :books do
    collection do
      put :update_attribute_on_the_spot
    end
    resources :notes, :only => [:create]
  end

  put 'notes/update'
  get 'notes/content', :as => :note_content
  resources :notes, :only => [:destroy]

  devise_for :users

  get "home/index"

  get "home/about", :as => :about

  root :to => 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :notes, :order => 'created_at desc'
  belongs_to :user

  after_create :add_first_note

  scope :from_user, lambda{ |user| where(:user_id => user.id) }

  def slug
    title.downcase.parameterize
  end

  protected

  def add_first_note
    self.notes.create
  end

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :book


  def display_content
    "<pre>#{content.present? && content.size > 0 ? CGI::escapeHTML(content) : '' } </pre>".html_safe
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :books
  has_many :notes, :through => :books

  after_create :add_first_book

  protected

  def add_first_book
    self.books.create(:title => 'Default')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!

  helper_method :current_user, :current_user?

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json

  can_edit_on_the_spot

  def index
    @books = Book.from_user(current_user)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])
    @book.user_id = current_user.id

    respond_to do |format|
      if @book.save
        #format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.html { redirect_to books_url, :flash => {:success => 'Book was successfully created.' } }
        format.json { render :json => @book, :status => :created, :location => @book }
      else
        format.html { render :action => "new" }
        format.json { render :json => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        #format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.html { redirect_to books_url, :notice => 'Book was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :ok }
      format.js
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:about]
  def index
  end

  def about
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  # retrieve note content before editing
  def content
    klass, field, id = params[:id].split('__')
    @note = Note.find(id)

    render :text => @note.content
  end


  # POST /notes
  # POST /notes.json
  def create
    @book = Book.find(params[:book_id])
    @note = Note.new(:book_id => @book.id, :content => '')

    respond_to do |format|
      if @note.save
        #format.html { redirect_to @note, :notice => 'Note was successfully created.' }
        #format.json { render :json => @note, :status => :created, :location => @note }
        format.js
      else
        #format.html { render :action => "new" }
        #format.json { render :json => @note.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /notes?id= ...
  # called from on_the_spot
  # to make sure we can return a correctly formatted view
  def update
    klass, field, id = params[:id].split('__')
    @note = current_user.notes.find(id)

    if @note.update_attributes(field => params[:value])
      render :text => "<pre>#{CGI::escapeHTML(@note.send(field))}</pre>", :status => 200
    else
      render :text => @note.errors.full_messages.join("\n"), :status => 422
    end
  end


  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    #@note = Note.find(params[:id])
    @note = current_user.notes.find(params[:id])
    @note.destroy

    respond_to do |format|
      #format.html { redirect_to notes_url }
      #format.json { head :ok }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def app_version
    "v#{APP_VERSION}".html_safe
  end

end

app/helpers/books_helper.rb
module BooksHelper
  include Haml::Helpers

  def editable_note(note)
    logger.debug "#### editable_note: note = #{note.inspect}"

    find_and_preserve(on_the_spot_edit note, :content, :type => :textarea, :onblur => 'submit',
                        :url => {:controller => :notes, :action => :update },
                        :loadurl => note_content_url,
                        :display_text => note.display_content)
  end

  #def display_note_content(note)
  #  find_and_preserve("<pre>#{content.present? ? CGI::escapeHTML(content) : '' } </pre>")
  #end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/books/_form.html.haml
= simple_form_for @book, :wrapper => 'inline' do |f|
  %fieldset
    %legend #{f.object.new_record? ? 'Create a new notebook' : 'Edit a notebook'}
    = f.input :title
    = f.input :description

    .actions
      = f.button :submit, :disable_with => 'Please wait ...'

app/views/books/destroy.js.erb
$("a[href='#<%= @book.slug %>']").parent().remove();
$("#<%= @book.slug %>").remove();
$('.tabs li').first().addClass('active');
$('.tab-content div').first().addClass('active');

app/views/books/edit.html.haml
= render 'form'

= link_to 'Show', @book
\|
= link_to 'Back', books_path

app/views/books/index.html.haml
%section#books
  .page-header
    %h1 Your notebooks

  %ul.tabs
    - first = true
    - @books.each do |book|
      %li{:class => first && 'active' }
        = link_to book.title, "##{book.slug}"
        - first = false

  .tab-content
    - first = true
    - @books.each do |book|
      %div{:id => "#{book.slug}", :class => first && 'active' }
        - first = false
        .book-container
          .note-actions
            = link_to 'delete notebook', book_path(book), :method => :delete, :confirm => "Are you sure you want to delete #{book.title}?", :remote => true
            = link_to 'new note', book_notes_path(book), :method => :post, :remote => true
          .note-content
            - book.notes.each do |note|
              -#%div{:id => "note-#{note.id}", :class => 'note'}
              -#  -#= on_the_spot_edit note, :content, :type => :textarea, :onblur => 'submit', :url => {:controller => :notes, :action => :update }
              -#  = editable_note(note)
              -#  .delete-note
              -#    = link_to 'delete note', note_path(note), :method => :delete, :confirm => 'Are you sure you want to delete this note?', :remote => true
              = render 'notes/note', :note => note

  =link_to 'Add a new book', new_book_path

app/views/books/new.html.haml
= render 'form'

= link_to 'Back', books_path

app/views/books/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @book.title
%p
  %b Description:
  = @book.description
%p
  %b User:
  = @book.user_id

= link_to 'Edit', edit_book_path(@book)
\|
= link_to 'Back', books_path

app/views/home/about.html.haml
%section#about
  .page-header
    %h1
      About
      %small hopefully what you wanted to know
  %blockquote
    Jottinx: the electronic equivalent of a small notebook to keep your brief (and hurriedly written) notes
  %p
    This is a small side-project, just scratching my own itch, I am an avid user of Google Notebook, but that could
    die every minute now (not really, but hey).
    So this site will mostly mimick the functionality of Google Notebook. Plain and simple note-keeping. Using markdown for formatting.

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Notebook
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

%body
  .topbar
    .topbar-inner
      .container
        %h3
          =link_to "Jottinx", root_url
        %ul.nav
          %li
            = link_to "Home", root_url
          %li
            = link_to "About", about_url
        %ul.nav.secondary-nav
          - if current_user
            %li{:class => 'dropdown', :'data-dropdown' => 'dropdown'}
              = link_to "Tools", '#', :class => 'dropdown-toggle'
              %ul.dropdown-menu
                %li
                  = link_to "Import Google notebook", '#'
                %li
                  = link_to "Do something else", '#'
                %li
                  = link_to "Your profile", '#'
                %li
                  = link_to "Logout", destroy_user_session_path, :method => :delete

  .container
    - flash.each do |name, msg|
      %div{:class => [name," alert-message"], :id => "flash_#{name}"}
        = msg
    = yield
  %footer.footer
    .container
      %p
        Jottinx is a
        = link_to '@dixis', 'http://twitter.com/dixis'
        realisation.
        %br
        = "&copy; 2011".html_safe
        |
        = app_version

:javascript
  var uvOptions = {};
  (function() {
    var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
    uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/yXRWlkle4k2oy5jElyPtA.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
  })();

app/views/notes/_note.html.erb
<div id="note-<%= note.id %>" class="note">
  <%= editable_note(note) %>
  <div class="delete-note">
    <%= link_to 'delete note', note_path(note), :method => :delete, :confirm => 'Are you sure you want to delete this note?', :remote => true %>
  </div>
</div>

app/views/notes/create.js.haml
:plain
    $("##{@book.slug} .note-content").prepend('#{j render(:partial => 'notes/note', :locals => {:note => @note}) }').fadeIn('slow');
    $('##{@book.slug} .note-content .on_the_spot_editing').each(initializeOnTheSpot);

app/views/notes/destroy.js.erb
$('#note-<%= @note.id %>').remove();